<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>
</head>
<body>
<div style="margin-top: 10px"> <h1>Уважаемый, ${user.firstName}</h1></div>
<h2>Пройдите для подтверждения регистрации по ссылке <a href="localhost/taxi-aggregator/api/confirm/${user.confirmCode}">ссылка</a></h2>
</body>
</html>
